"""
Looks for content-provenance markers that image generators embed in a file.

An image regenerated by an AI tool (for example ChatGPT editing a prescription)
has no local splice for the forgery model or ELA to find. What it often does
carry is a provenance marker: C2PA / JUMBF content credentials, the IPTC
"trainedAlgorithmicMedia" digital-source-type, or a generator name in XMP / PNG
text chunks.

Limits: a marker that IS present is a strong signal. A marker that is ABSENT
proves nothing (a screenshot, a WhatsApp forward or a re-save removes it).
Never treat "no marker" as "not AI-edited".

Pure function over the raw uploaded bytes. No I/O, no model, no network.
"""
from __future__ import annotations

from dataclasses import dataclass, field

_STRONG_MARKERS: tuple[tuple[bytes, str], ...] = (
    (b"trainedalgorithmicmedia", "IPTC digital source type: AI-generated media"),
    (b"compositewithtrainedalgorithmicmedia", "IPTC digital source type: AI-edited composite"),
    (b"algorithmicmedia", "IPTC digital source type: algorithmic media"),
    (b"c2pa", "C2PA content credentials present"),
    (b"cabx", "C2PA content-credentials chunk present"),
)

_GENERATOR_NAMES: tuple[tuple[bytes, str], ...] = (
    (b"openai", "Generator name in metadata: OpenAI"),
    (b"chatgpt", "Generator name in metadata: ChatGPT"),
    (b"dall-e", "Generator name in metadata: DALL-E"),
    (b"midjourney", "Generator name in metadata: Midjourney"),
    (b"stable diffusion", "Generator name in metadata: Stable Diffusion"),
    (b"adobe firefly", "Generator name in metadata: Adobe Firefly"),
    (b"imagen", "Generator name in metadata: Imagen"),
    (b"synthid", "SynthID reference in metadata"),
)


@dataclass(frozen=True)
class ProvenanceResult:
    ai_marker_found: bool
    flags: list[str] = field(default_factory=list)
    no_camera_metadata: bool = False


def _has_exif(raw: bytes) -> bool:
    return b"Exif\x00\x00" in raw[:65536] or b"eXIf" in raw[:65536]


def detect_ai_provenance(raw: bytes) -> ProvenanceResult:
    """Scan the raw uploaded bytes for AI-provenance markers."""
    lowered = raw.lower()
    flags: list[str] = []

    for needle, message in _STRONG_MARKERS:
        if needle in lowered and message not in flags:
            flags.append(message)

    # "jumb" is only 4 bytes; require its box type "jumd" beside it so random
    # compressed data cannot trigger it.
    if b"jumb" in lowered and b"jumd" in lowered:
        message = "JUMBF metadata box present (C2PA container)"
        if message not in flags:
            flags.append(message)

    for needle, message in _GENERATOR_NAMES:
        if needle in lowered and message not in flags:
            flags.append(message)

    return ProvenanceResult(
        ai_marker_found=bool(flags),
        flags=flags,
        no_camera_metadata=not _has_exif(raw),
    )